---

version: 26.1

emacs:
  tarball:
    name: "emacs-{{ version }}.tar.gz"
    url: "ftp://ftp.gnu.org/pub/gnu/emacs/emacs-{{ version }}.tar.gz"
  sig:
    name: "emacs-{{ version }}.tar.gz.sig"
    url: "ftp://ftp.gnu.org/pub/gnu/emacs/emacs-{{ version }}.tar.gz.sig"

source: "{{ DOWNLOADS }}/emacs-{{ version }}"
tar: "{{ DOWNLOADS }}/emacs-{{ version }}.tar.gz"

init_git: "git@github.com:kaustubhkurve/.emacs.d.git"

build_packages:
   - libm17n-dev
   - m17n-db
   - libotf-dev 
   - libxpm4
   - libxpm-dev
   - libpng-dev
   - libz3-dev 
   - libjpeg-dev 
   - libtiff-dev 
   - libgif-dev 
   - librsvg2-dev 
   - libgtk2.0-dev
   - texinfo 
   - libx11-dev 
   - libncurses5-dev 
   - build-essential
   - libgnutls28-dev

