---

# Install and configure system tools

- name: Install system packages
  apt:
    name: "{{item}}"
    state: latest
  with_items: "{{packages}}"
  become: yes

- name: Install Oh-my-Zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'

- name: Clone dotfiles repo
  git:
    repo: '{{ dotfiles_git }}'
    dest: '{{ lookup("env", "HOME") }}/dotfiles'
    version: "master"

- name: Setup dotfiles
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item.src }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ dotfiles }}"
