---

# Installing the build dependencies used by emacs package provided
# by the distribution. Let's see if that works.
- name: Install emacs build dependencies
  apt:
    pkg: emacs
    state: build-dep
  become: yes

- name: Install additional packages
  apt:
    name: "{{ build_packages }}"
  become: yes

- name: Run Configure
  shell: './configure'
  args:
    chdir: "{{ source }}"

- name: Run Make
  shell: 'make'
  args:
    chdir: "{{ source }}"

- name: Run Make Install
  shell: 'make install'
  args:
    chdir: "{{ source }}"
  become: yes
