---

- name: Download Adobe Source Code Pro
  get_url:
    url: 'https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz'
    dest: '{{ DOWNLOADS }}/source-code-pro.tar.gz'

- name: Unzip Source Code Pro
  unarchive:
    src: '{{ DOWNLOADS }}/source-code-pro.tar.gz'
    dest: '{{ DOWNLOADS }}'

- name: Create Font directory
  shell: 'mkdir -p /usr/share/fonts/source-code-pro'
  become: yes

- name: Install Source Code Pro Font
  copy:
    src: '{{ item }}'
    dest: '/usr/share/fonts/source-code-pro/'
  with_fileglob: "{{ DOWNLOADS }}/source-code-pro-2.030R-ro-1.050R-it/OTF/*.otf"
  become: yes

- name: Regenerate font cache
  shell: 'fc-cache -f -v'
  become: yes
