---

- name: Download Adobe Source Code Pro
  get_url:
    url: 'https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz'
    dest: '{{ DOWNLOADS }}/source-code-pro.tar.gz'

- name: Unzip Source Code Pro
  shell: 'tar -xvzf source-code-pro.tar.gz'
  arg:
    chdir: '{{ DOWNLOADS }}'

- name: Create Font directory
  shell: 'mkdir -p /usr/share/fonts/source-code-pro'
  become: yes

- name: Install Source Code Pro Font
  shell: 'cp source-code-pro/OTF/*.otf /usr/share/fonts/source-code-pro/'
  arg:
    chdir: '{{ DOWNLOADS }}'
  become: yes

- name: Regenerate font cache
  shell: 'fc-cache -f -v'
  become: yes
